#line 2 "markdown.lex.c"

#line 4 "markdown.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 46
#define YY_END_OF_BUFFER 47
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[150] =
    {   0,
       47,   44,   46,   45,   46,   44,   46,    8,   44,   46,
       11,   44,   46,   44,   46,16408,16409,    1,   45,   46,
       44,   46,   44,   46,   31,   44,   46,   44,   46,   44,
       46,   44,   46,    7,   44,   46,   10,   46,   46,    9,
       10,   46,   27,   46,   28,   46,   27,   46,   13,   46,
       14,   46,   46,   14,   46,   15,   46,   17,   46,   18,
       46,   17,   46,   17,   46,   46,   46,   46,   34,   46,
       35,   46,   34,   46,   37,   46,   38,   46,   37,   46,
       37,   46,   41,   46,   42,   46,   41,   46,   41,   46,
       45,   16,   26,   26,16408,16409,    1,   26,   26,   26,

       26,    1,   45,   31,   20,    2,   27,   28,   13,   14,
       12,   18,   19,   29,   34,   35,   38,   42, 8216,   31,
       22,   33,    3,   32,   30, 8217,16408,16409,   31,    4,
       32,   21,   31,    5,   32,   23,   31,    6,   32,   33,
    16424,   32,   33,16420,   32,   43,   39, 8232, 8228
    } ;

static yyconst flex_int16_t yy_accept[497] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        4,    6,    8,   11,   14,   18,   21,   23,   25,   28,
       30,   32,   34,   37,   39,   40,   43,   45,   47,   49,
       51,   53,   54,   56,   58,   60,   62,   64,   66,   67,
       68,   69,   71,   73,   75,   77,   79,   81,   83,   85,
       87,   89,   91,   92,   93,   94,   97,   98,   99,  100,
      101,  102,  104,  104,  104,  104,  104,  104,  105,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,

      106,  106,  106,  106,  106,  107,  107,  107,  108,  109,
      110,  111,  112,  113,  114,  114,  114,  114,  115,  115,
      115,  116,  117,  118,  118,  119,  119,  119,  119,  119,
      120,  120,  120,  120,  121,  122,  122,  122,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,

      123,  123,  123,  123,  123,  124,  124,  124,  125,  125,
      125,  125,  126,  126,  126,  126,  127,  129,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  131,
      131,  131,  132,  133,  133,  133,  133,  133,  134,  134,

      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  135,  135,
      135,  136,  137,  137,  137,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,

      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      139,  139,  139,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  142,
      142,  142,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  145,  145,
      145,  145,  145,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  147,  147,  147,  147,  147,  147,
      147,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  149,  149,  150,  150

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    1,    7,    1,    1,    1,    1,    6,
        6,    8,    8,    1,    9,   10,   11,   12,   13,   13,
       13,   13,   13,   13,   14,   14,   14,    1,    1,   15,
        1,   16,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   17,    1,    1,    6,   18,   19,   20,   21,   22,

       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,    1,    6,    1,    6,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[44] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[516] =
    {   0,
        0,   17,   33,   49,    2,    4,   10,   43,   45,   50,
       57,   64,    6,    8,   70,   72,   76,   78,  953,  954,
      954,  949,  954,  933,   92,  954,  947,  105,  942,  943,
       76,  109,   98,  954,  954,  954,    0,  954,  944,    0,
      954,  943,  927,  954,  954,  954,  941,  925,  147,  937,
      111,    0,  954,  938,  954,  954,  937,  928,  954,  954,
      935,  926,  954,  954,  954,  160,  954,  933,  173,  930,
      144,  954,  167,  931,  928,  927,  170,  924,  925,  924,
      178,   27,  177,  201,  177,  222,  897,  176,  212,  227,
       92,  199,  103,    4,  185,  211,  911,  168,  249,  270,

       68,  140,  906,  894,  954,  921,  306,    0,  954,    0,
      954,  954,  954,  954,  248,  918,  261,  917,  916,  288,
        0,  954,  954,  883,  954,  882,  913,  912,  311,  911,
      910,  316,  909,  906,  907,   78,  895,  954,  169,  101,
      179,  205,  253,  239,  216,   67,  251,  217,  270,  241,
      894,  261,  247,  877,  870,  305,  869,  274,  874,  297,
      302,  282,  306,  886,  885,  872,  315,  316,  318,  327,
      880,  858,  880,  874,   13,  310,  315,  858,  129,  869,
      858,  857,  324,  333,  874,  163,  329,  341,  342,   95,
      348,  332,  343,  873,  859,  849,  857,  213,  338,  354,

      853,  866,  851,  852,  954,  882,  375,  877,  878,  371,
      374,  877,  860,  842,  874,  873,  387,  870,  370,  377,
      378,  382,  380,  381,  383,  391,  387,  392,  389,  401,
      388,  279,  836,  837,  836,  850,  849,  405,  840,  851,
      850,  838,  409,  837,  389,  828,  827,  833,  832,  840,
      831,  407,  408,  411,  835,  836,  835,  413,  828,  817,
      414,  819,  833,  830,  409,  818,  419,  423,  808,  424,
      425,  334,  428,  429,  430,  433,  434,  438,  439,  820,
      827,  810,  814,  437,  823,  815,  441,  821,  954,  840,
      468,  835,  836,  835,  464,  803,  795,  830,  448,  453,

      447,  464,  465,  468,  469,  466,  470,  474,  475,  817,
      808,  811,  477,  814,  802,  804,  797,  479,  807,  809,
      791,  803,  802,  481,  480,  482,  484,  801,  793,  790,
      489,  785,  801,  783,  797,  781,  783,  776,  486,  491,
      494,  496,  493,  499,  503,  502,  505,  509,  514,  791,
      770,  793,  773,  518,  787,  506,  776,  954,  805,  538,
      800,  801,  778,  774,  954,  510,  522,  520,  523,  530,
      531,  532,  534,  535,  766,  769,  765,  533,  768,  772,
      768,  772,  759,  761,  771,  757,  536,  538,  539,  541,
      760,  769,  537,  759,  762,  750,  754,  732,  723,  554,

      540,  543,  542,  556,  565,  566,  712,  567,  691,  954,
      723,  585,  718,  690,  700,  568,  555,  571,  573,  569,
      579,  690,  581,  699,  683,  682,  695,  679,  584,  586,
      588,  693,  681,  675,  589,  697,  593,  693,  606,  596,
      680,  695,  656,  671,  597,  598,  599,  639,  637,  644,
      600,  601,  590,  422,  251,  603,  238,  619,  626,  632,
      633,  189,  954,  111,   12,  608,   59,  638,  639,  641,
      645,  647,  654,  954,  658,  606,   12,  651,  655,  660,
      954,  664,  665,  661,  669,  668,  670,  677,  674,  675,
      691,  692,  695,  697,  954,  729,  732,  735,  738,  741,

      744,  747,  750,  753,  756,  759,    0,  762,  765,  768,
      771,  774,  777,  780,  783
    } ;

static yyconst flex_int16_t yy_def[516] =
    {   0,
      496,  496,  497,  497,  498,  498,  499,  499,  500,  500,
      501,  501,  502,  502,  503,  503,  504,  504,  495,  495,
      495,  495,  495,  495,  505,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  506,  495,  506,  507,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  508,  495,  508,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  505,  495,  495,  495,  495,
      495,  495,  495,  495,   28,  495,  495,  495,  495,  495,
      495,   32,  509,  509,  495,  495,  495,  495,  495,  509,
      495,  495,  495,  495,  495,  509,  509,  495,  509,  495,

      509,  495,  495,  495,  495,  495,  495,  506,  495,  507,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      508,  495,  495,  495,  495,  495,   69,  495,  495,  495,
      495,  495,   28,  495,  495,   99,  509,  495,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  495,  495,  495,  495,  495,  495,  495,  495,
      509,  495,  495,  495,  495,  495,  509,  509,  509,  509,
      495,  495,  495,  495,  509,  495,  495,  495,  495,  495,
      495,  495,  509,  509,  495,  509,  509,  509,  509,  509,
      509,  509,  509,  495,  495,  495,  495,  509,  495,  509,

      495,  495,  495,  495,  495,  495,  107,  495,  495,  495,
      495,  495,  495,  495,   69,  495,  505,  495,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  509,
      509,  509,  495,  495,  495,  495,  495,  509,  495,  495,
      495,  495,  509,  495,  495,  495,  495,  495,  495,  495,
      495,  509,  509,  509,  495,  495,  495,  509,  495,  495,
      495,  495,  495,  495,  495,  495,  509,  509,  495,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  495,
      495,  495,  495,  509,  495,  495,  509,  495,  495,  495,
      107,  495,  495,  495,  495,  495,  495,  495,  509,  509,

      509,  509,  509,  509,  509,  509,  509,  509,  509,  495,
      495,  495,  509,  495,  495,  495,  495,  509,  495,  495,
      495,  495,  495,  509,  509,  509,  509,  495,  495,  495,
      509,  495,  495,  495,  495,  495,  495,  495,  509,  509,
      509,  509,  509,  509,  509,  509,  509,  509,  509,  495,
      495,  495,  495,  509,  495,  509,  495,  495,  495,  107,
      495,  495,  495,  495,  495,  509,  509,  509,  509,  509,
      509,  509,  509,  509,  495,  495,  495,  509,  495,  495,
      495,  495,  495,  495,  495,  495,  509,  509,  509,  509,
      495,  495,  509,  495,  495,  495,  495,  495,  495,  509,

      509,  509,  509,  509,  509,  509,  510,  509,  495,  495,
      495,  495,  495,  495,  495,  509,  509,  509,  509,  509,
      509,  495,  509,  495,  495,  495,  495,  495,  509,  509,
      509,  495,  495,  495,  509,  511,  509,  510,  512,  509,
      495,  495,  495,  495,  509,  509,  509,  495,  495,  495,
      509,  509,  495,  495,  495,  509,  511,  513,  512,  512,
      512,  495,  495,  495,  514,  509,  495,  513,  513,  513,
      512,  515,  514,  495,  514,  509,  495,  513,  512,  515,
      495,  515,  513,  512,  513,  512,  513,  512,  513,  512,
      513,  512,  513,  513,    0,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495
    } ;

static yyconst flex_int16_t yy_nxt[998] =
    {   0,
      110,  495,   21,   22,   38,   39,   38,   39,   53,   54,
       53,   54,   41,   42,  474,  475,   23,   24,   25,   26,
       27,   28,  178,   29,   30,   30,   43,   44,  138,   31,
       31,   32,   33,   23,   24,   35,  179,  495,   36,   36,
       36,   36,   36,   97,  258,   41,   42,   46,   47,   36,
       36,   35,   46,   47,   36,   36,   36,   36,   36,   43,
       44,   49,   48,  136,   50,   36,   36,   48,   49,   51,
       51,   50,   56,   57,   56,   57,   51,   51,   60,   61,
       60,   61,  138,  138,   58,   80,   58,   81,   81,   81,
       62,  477,   62,   66,   67,   68,   69,  151,  219,   70,

      105,  106,  107,  229,   71,   71,   73,   67,   74,   75,
      138,  171,   76,   76,  172,  220,  138,   77,   77,   82,
      119,  176,  120,  120,  120,  177,  472,   83,   84,   85,
       86,   87,   88,  275,   89,   90,  222,   91,   92,   93,
       94,   95,   96,   97,   98,   99,  100,  101,  102,  103,
      104,  115,  262,  131,  116,  132,  132,  132,  201,  117,
      117,   66,   67,   68,   69,  263,  202,   70,   73,   67,
       74,   73,   71,   71,   73,   67,   74,  127,  138,   80,
      128,   81,   81,   81,  138,  129,  129,   80,  221,   81,
       81,   81,  138,  270,  138,  153,  139,  140,  141,  154,

      223,   97,  162,  155,  180,   97,  185,   97,  163,  156,
      142,  164,  143,  144,   97,  145,  138,  173,  181,  146,
      138,  174,  147,  182,   97,  175,  138,  148,  138,  183,
      149,  138,  138,  150,  165,  284,  151,  228,  224,  152,
      157,  151,  138,   97,  158,  159,  184,   97,  160,  166,
      167,   97,  211,  458,  138,  116,  138,  168,  169,   97,
      117,  117,  231,  170,  138,  227,  138,  186,  138,  187,
      119,  188,  120,  120,  120,  225,  138,  151,  233,  189,
      234,  190,  191,  151,   97,  138,  192,  193,  194,  195,
      226,   97,  196,  197,  138,  198,  199,  119,  232,  120,

      120,  120,  230,   97,  244,  200,  245,   97,  205,  206,
      207,  241,  208,  209,  209,  242,  309,  138,  210,  210,
      131,  243,  132,  132,  132,  131,  237,  132,  132,  132,
      138,  138,   97,  138,  238,  239,   97,  246,  247,  138,
      151,  248,  138,   97,  138,  259,  260,  138,  138,  138,
      252,  253,  261,  254,  151,  151,  138,  138,  138,  267,
      274,  272,  151,  138,  271,  268,  276,  277,  285,  138,
      273,  342,  287,  279,  278,  286,  151,  289,  290,  291,
      294,  116,  295,  295,  295,  138,  117,  117,   66,   67,
       68,   69,  138,  138,   70,  138,  138,  138,  138,   71,

       71,  151,  138,  138,  138,  299,  138,  138,  305,  320,
      303,  307,  277,  151,  301,  302,  138,  304,  306,  300,
      138,  308,  138,  138,  138,  325,  138,  321,  138,  313,
      151,  318,   97,  336,  138,  337,  332,  339,  138,  138,
      138,  151,  327,  138,  138,  138,  326,  340,  138,  138,
      343,  341,  138,  138,  138,  354,  138,  151,  344,   97,
      346,  356,  138,  138,  151,  345,  347,  348,  138,  349,
      358,  359,  360,  294,  366,  295,  295,  295,  368,  138,
      138,  138,  367,  138,  138,  138,  369,  370,  371,  138,
      138,  151,  138,  372,  138,  138,  138,  138,  151,  138,

      151,  138,  373,  388,  138,  390,  138,  374,  138,  138,
      389,  138,  378,  403,  138,  393,  151,  138,  138,  151,
      138,  138,  402,  404,  138,  138,  400,  401,  151,  138,
      405,  407,  408,  138,  151,  138,  406,  138,  138,  151,
      410,  411,  412,  416,  151,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  418,
      419,  151,  417,  430,  420,  423,  151,  151,  421,  138,
      138,  138,  429,  151,  431,  437,  435,  436,  151,  151,
      138,  138,  138,  138,  138,  151,  138,  151,  138,  412,
      151,  208,  209,  209,  138,  151,  138,  210,  210,  138,

      445,  138,  440,  138,  138,  151,  451,  151,  138,  460,
      452,  138,  138,  138,  138,  138,  138,  446,  138,  447,
      461,  138,  469,  138,  151,  456,   97,  151,  151,  460,
      466,  151,  151,  470,  151,  460,  460,  151,  151,  151,
      461,  469,  469,  471,  469,  476,  461,  461,  460,  481,
      482,  478,  470,  470,  469,  470,  474,  475,  460,  461,
      474,  475,  481,  482,  460,  470,  481,  482,  469,  461,
      467,  460,  469,  469,   97,  461,   97,  469,  460,  470,
      460,  479,  461,  470,  470,  485,  465,  483,  470,  461,
      492,  461,  484,  464,  469,  460,  489,  488,  469,  490,

      469,  463,  462,  486,  487,  470,  461,  491,  439,  470,
      494,  470,  458,  455,  454,  453,  450,  449,   97,  448,
       97,   97,  444,  443,  442,  410,  441,  439,  493,   20,
       20,   20,   34,   34,   34,   37,   37,   37,   40,   40,
       40,   45,   45,   45,   35,   35,   35,   52,   52,   52,
       55,   55,   55,   59,   59,   59,   65,   65,   65,  108,
       97,  108,  121,   97,  121,  137,  137,  137,  438,  438,
      438,  457,  457,  457,  459,  459,  459,  468,  468,  468,
      473,  473,  473,  480,  480,  480,  434,   97,  433,  432,
       97,   97,   97,   97,  428,  427,   97,  426,  425,  424,

       97,  422,   97,  415,  414,  362,  413,  358,   97,   97,
       97,  409,   97,   97,  399,  398,  397,  396,  395,  394,
       97,  392,   97,  391,  387,  386,  385,  384,  383,  382,
      381,  380,  379,  377,  376,  375,  365,  364,  363,  362,
      293,  361,  289,  357,  355,   97,  353,  352,  351,  350,
       97,  338,  335,  334,  333,  331,   97,  330,  329,  328,
       97,  324,  323,   97,  322,   97,  319,  317,  316,  315,
      314,   97,   97,  312,  311,  310,  298,  216,  217,  297,
      296,  212,  293,  292,  205,   97,   97,  288,   97,  283,
      282,  281,  280,  269,  266,  265,  264,   97,  257,  256,

      255,   97,  251,  250,  249,   97,  240,  236,  235,  138,
      138,  135,  218,  217,  216,  130,  130,  215,  214,  213,
      212,  118,  118,  105,  204,  203,  138,  161,  135,   79,
      134,   79,  133,   67,  130,   67,  126,  125,  124,  123,
      122,  118,  114,  113,  112,  111,  109,   79,   78,   72,
       64,   63,  495,   19,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495

    } ;

static yyconst flex_int16_t yy_chk[998] =
    {   0,
      507,    0,    1,    1,    5,    5,    6,    6,   13,   13,
       14,   14,    7,    7,  465,  465,    1,    1,    2,    2,
        2,    2,   94,    2,    2,    2,    7,    7,  175,    2,
        2,    2,    2,    2,    2,    3,   94,   82,    3,    3,
        3,    3,    3,  477,  175,    8,    8,    9,    9,    3,
        3,    4,   10,   10,    4,    4,    4,    4,    4,    8,
        8,   11,    9,   82,   11,    4,    4,   10,   12,   11,
       11,   12,   15,   15,   16,   16,   12,   12,   17,   17,
       18,   18,  146,  101,   15,   31,   16,   31,   31,   31,
       17,  467,   18,   25,   25,   25,   25,  101,  136,   25,

       33,   33,   33,  146,   25,   25,   28,   28,   28,   28,
      190,   91,   28,   28,   91,  136,  140,   28,   28,   32,
       51,   93,   51,   51,   51,   93,  464,   32,   32,   32,
       32,   32,   32,  190,   32,   32,  140,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   49,  179,   71,   49,   71,   71,   71,  102,   49,
       49,   66,   66,   66,   66,  179,  102,   66,   73,   73,
       73,   73,   66,   66,   69,   69,   69,   69,  186,   77,
       69,   77,   77,   77,  139,   69,   69,   81,  139,   81,
       81,   81,   83,  186,  141,   85,   83,   83,   83,   85,

      141,   98,   88,   85,   95,   98,   98,  462,   88,   85,
       83,   88,   83,   83,   95,   83,   84,   92,   95,   84,
      142,   92,   84,   95,   89,   92,   96,   84,  198,   96,
       84,  145,  148,   84,   89,  198,   84,  145,  142,   84,
       86,  148,   90,   86,   86,   86,   96,   89,   86,   89,
       90,   86,  115,  457,  144,  115,  150,   90,   90,   86,
      115,  115,  150,   90,   99,  144,  147,   99,  143,   99,
      117,   99,  117,  117,  117,  143,  152,  147,  153,   99,
      153,   99,   99,  147,  455,  149,   99,   99,  100,  100,
      143,  100,  100,  100,  232,  100,  100,  120,  152,  120,

      120,  120,  149,  158,  162,  100,  162,  100,  107,  107,
      107,  158,  107,  107,  107,  160,  232,  161,  107,  107,
      129,  161,  129,  129,  129,  132,  156,  132,  132,  132,
      167,  168,  160,  169,  156,  156,  160,  163,  163,  183,
      168,  163,  170,  176,  187,  176,  177,  192,  184,  272,
      167,  169,  177,  170,  169,  184,  188,  189,  193,  183,
      189,  188,  193,  191,  187,  184,  191,  192,  199,  200,
      188,  272,  200,  193,  192,  199,  193,  207,  207,  207,
      210,  211,  210,  210,  210,  219,  211,  211,  217,  217,
      217,  217,  220,  221,  217,  223,  224,  222,  225,  217,

      217,  225,  227,  231,  229,  219,  226,  228,  227,  245,
      224,  229,  220,  221,  222,  223,  230,  226,  228,  220,
      238,  230,  252,  253,  243,  252,  254,  245,  258,  238,
      231,  243,  261,  265,  267,  265,  261,  267,  268,  270,
      271,  258,  254,  273,  274,  275,  253,  268,  276,  277,
      273,  271,  284,  278,  279,  284,  287,  270,  274,  454,
      277,  287,  301,  299,  276,  275,  277,  278,  300,  279,
      291,  291,  291,  295,  299,  295,  295,  295,  301,  302,
      303,  306,  300,  304,  305,  307,  302,  303,  304,  308,
      309,  305,  313,  307,  318,  325,  324,  326,  306,  327,

      318,  339,  308,  324,  331,  327,  340,  309,  343,  341,
      325,  342,  313,  343,  344,  331,  339,  346,  345,  326,
      347,  356,  342,  345,  348,  366,  340,  341,  344,  349,
      346,  348,  349,  354,  356,  368,  347,  367,  369,  354,
      360,  360,  360,  366,  367,  370,  371,  372,  378,  373,
      374,  387,  393,  388,  389,  401,  390,  403,  402,  369,
      371,  389,  368,  390,  372,  378,  374,  370,  373,  400,
      417,  404,  387,  388,  393,  402,  400,  401,  404,  403,
      405,  406,  408,  416,  420,  417,  418,  405,  419,  412,
      406,  412,  412,  412,  421,  419,  423,  412,  412,  429,

      420,  430,  408,  431,  435,  416,  429,  418,  437,  439,
      431,  440,  445,  446,  447,  451,  452,  421,  456,  423,
      439,  476,  458,  466,  437,  435,  453,  430,  476,  459,
      446,  452,  447,  458,  445,  460,  461,  451,  440,  456,
      459,  468,  469,  461,  470,  466,  460,  461,  471,  472,
      472,  470,  468,  469,  478,  470,  473,  473,  479,  471,
      475,  475,  480,  480,  484,  478,  482,  482,  483,  479,
      450,  486,  485,  487,  449,  484,  448,  489,  490,  483,
      488,  471,  486,  485,  487,  483,  444,  478,  489,  490,
      490,  488,  479,  443,  491,  492,  487,  486,  493,  488,

      494,  442,  441,  484,  485,  491,  492,  489,  438,  493,
      493,  494,  436,  434,  433,  432,  428,  427,  426,  425,
      424,  422,  415,  414,  413,  411,  409,  407,  491,  496,
      496,  496,  497,  497,  497,  498,  498,  498,  499,  499,
      499,  500,  500,  500,  501,  501,  501,  502,  502,  502,
      503,  503,  503,  504,  504,  504,  505,  505,  505,  506,
      399,  506,  508,  398,  508,  509,  509,  509,  510,  510,
      510,  511,  511,  511,  512,  512,  512,  513,  513,  513,
      514,  514,  514,  515,  515,  515,  397,  396,  395,  394,
      392,  391,  386,  385,  384,  383,  382,  381,  380,  379,

      377,  376,  375,  364,  363,  362,  361,  359,  357,  355,
      353,  352,  351,  350,  338,  337,  336,  335,  334,  333,
      332,  330,  329,  328,  323,  322,  321,  320,  319,  317,
      316,  315,  314,  312,  311,  310,  298,  297,  296,  294,
      293,  292,  290,  288,  286,  285,  283,  282,  281,  280,
      269,  266,  264,  263,  262,  260,  259,  257,  256,  255,
      251,  250,  249,  248,  247,  246,  244,  242,  241,  240,
      239,  237,  236,  235,  234,  233,  218,  216,  215,  214,
      213,  212,  209,  208,  206,  204,  203,  202,  201,  197,
      196,  195,  194,  185,  182,  181,  180,  178,  174,  173,

      172,  171,  166,  165,  164,  159,  157,  155,  154,  151,
      137,  135,  134,  133,  131,  130,  128,  127,  126,  124,
      119,  118,  116,  106,  104,  103,   97,   87,   80,   79,
       78,   76,   75,   74,   70,   68,   62,   61,   58,   57,
       54,   50,   48,   47,   43,   42,   39,   30,   29,   27,
       24,   22,   19,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495

    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "markdown.lex"
#line 2 "markdown.lex"

#include <string.h>
#include "blocknode.h"
#include "markdown.y.h"

#undef _ISDEBUGLEX

#ifdef _ISDEBUGLEX
#define P(token) printf("token: %s\n", token); BeginToken(yytext);
#else
#define P(token) BeginToken(yytext);
#endif

#define YY_INPUT(buf,result,max_size)  { \
    result = GetNextChar(buf, max_size); \
    if (  result <= 0  ) \
      result = YY_NULL; \
}

/* prototypes */
int yylineno;

/* input.c */
int GetNextChar(char *b, int maxBuffer);
void BeginToken(char *t);;

 

/* blankline ^[ ]{0,4}\r?\n */
#line 901 "markdown.lex.c"

#define INITIAL 0
#define ESCAPE 1
#define CODEBLOCK 2
#define CODESPAN 3
#define XCODESPAN 4
#define INDENTLIST 5
#define SHTMLBLOCK 6
#define SCRIPTBLOCK 7
#define STYLEBLOCK 8

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 37 "markdown.lex"


    /* special chars: "\[]^-?.*+|()$/{}%<> */

#line 1099 "markdown.lex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 496 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 954 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
goto find_rule; /* Shut up GCC warning -Wall */
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 41 "markdown.lex"
{ yylineno++; P("BLANKLINE"); return BLANKLINE; }
	YY_BREAK
/* !!! note: quoteblankline has no effect */
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 43 "markdown.lex"
{ yylineno++; P("QUOTEBLANKLINE"); return QUOTEBLANKLINE; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 44 "markdown.lex"
{ yylineno++; P("QUOTEBLANKLINE"); return QUOTEBLANKLINE; }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 45 "markdown.lex"
{ yylineno++; P("QUOTEBLANKLINE"); return QUOTEBLANKLINE; }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 46 "markdown.lex"
{ yylineno++; P("QUOTEBLANKLINE"); return QUOTEBLANKLINE; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 47 "markdown.lex"
{ yylineno++; P("QUOTEBLANKLINE"); return QUOTEBLANKLINE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 49 "markdown.lex"
{ P("LARGERTHAN"); return LARGERTHAN; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 52 "markdown.lex"
{ P("ESCAPE"); BEGIN ESCAPE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 53 "markdown.lex"
{ BEGIN INITIAL; yylval.text = strdup(yytext); P("SPECIALCHAR"); return SPECIALCHAR; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 54 "markdown.lex"
{ BEGIN INITIAL; yylval.text = strdup(yytext); P("SPECIALCHAR"); return SPECIALCHAR; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 56 "markdown.lex"
{ P("BACKTICK"); BEGIN CODESPAN; return BACKTICK; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 57 "markdown.lex"
{ P("SPECIALCHAR"); 
                                            yylval.text = strdup("`"); return SPECIALCHAR; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 59 "markdown.lex"
{ P("CODETEXT"); yylval.text = strdup(yytext); return CODETEXT; }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 60 "markdown.lex"
{ P("CODETEXT"); yylval.text = strdup(yytext); 
                                            yylineno++; return CODETEXT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 62 "markdown.lex"
{ P("BACKTICK"); BEGIN INITIAL; return BACKTICK; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 64 "markdown.lex"
{ P("DOUBLEBACKTICK"); BEGIN XCODESPAN; return DOUBLEBACKTICK; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 65 "markdown.lex"
{ P("CODETEXT"); yylval.text = strdup(yytext); return CODETEXT; }
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 66 "markdown.lex"
{ P("CODETEXT"); yylval.text = strdup(yytext);
                                            yylineno++; return CODETEXT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 68 "markdown.lex"
{ P("DOUBLEBACKTICK"); BEGIN INITIAL; return DOUBLEBACKTICK; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 72 "markdown.lex"
{ P("ULSTART"); return ULSTART; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 73 "markdown.lex"
{ P("QUOTEULSTART"); return QUOTEULSTART; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 74 "markdown.lex"
{ P("OLSTART"); return OLSTART; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 75 "markdown.lex"
{ P("QUOTEOLSTART"); return QUOTEOLSTART; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 79 "markdown.lex"
{ 
                                            /* indent ul list */
                                            if(is_in_list(indent_level(yytext))){
                                                BEGIN INDENTLIST;
                                                yylval.text = strdup(yytext);
                                                P("INDENT"); return INDENT; 
                                            }
                                            else{
                                                BEGIN CODEBLOCK; 
                                                yylval.text = strdup(yytext);
                                                P("INDENT"); return INDENT;
                                            }
                                        }   
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 92 "markdown.lex"
{ 
                                            /* indent ol list */
                                            if(is_in_list(indent_level(yytext))){
                                                BEGIN INDENTLIST;
                                                yylval.text = strdup(yytext);
                                                P("INDENT"); return INDENT; 
                                            }
                                            else{
                                                BEGIN CODEBLOCK; 
                                                yylval.text = strdup(yytext);
                                                P("INDENT"); return INDENT;
                                            }
                                        }   
	YY_BREAK
case 26:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 105 "markdown.lex"
{ 
                                            /* indent p */
                                            if(is_in_list(indent_level(yytext))){
                                                yylval.text = strdup(yytext);
                                                P("INDENT"); return INDENT; 
                                            }
                                            else{
                                                BEGIN CODEBLOCK; 
                                                yylval.text = strdup(yytext);
                                                P("INDENT"); return INDENT;
                                            }
                                        }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 117 "markdown.lex"
{ yylval.text = strdup(yytext); P("CODETEXT"); return CODETEXT; }
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 118 "markdown.lex"
{ P(""); BEGIN INITIAL; yylineno++; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 120 "markdown.lex"
{ BEGIN INITIAL; P("ULSTART"); return ULSTART; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 121 "markdown.lex"
{ BEGIN INITIAL; P("OLSTART"); return OLSTART; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 124 "markdown.lex"
{ yylval.text = strdup(yytext); P("H"); return H; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 125 "markdown.lex"
{ yylval.text = strdup(yytext); P("QUOTEH"); return QUOTEH; }
	YY_BREAK
/* block and functional html tags must be in one line and must start at first column */
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 128 "markdown.lex"
{ 
                                            yylval.text = strdup(yytext); 
                                            P("HTMLBLOCK"); 
                                            BEGIN SHTMLBLOCK; 
                                            return HTMLBLOCK; 
                                        }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 134 "markdown.lex"
{ yylval.text = strdup(yytext); P("TEXT"); return TEXT; }
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 135 "markdown.lex"
{ yylineno++; P("LINEBREAK"); BEGIN INITIAL;  return LINEBREAK; }
	YY_BREAK
/* script block */
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 140 "markdown.lex"
{
                                            yylval.text = strdup(yytext); 
                                            P("SCRIPTSTART"); 
                                            BEGIN SCRIPTBLOCK; 
                                            return SCRIPTSTART; 
                                        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 146 "markdown.lex"
{ yylval.text = strdup(yytext); P("TEXT"); return TEXT; }
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 147 "markdown.lex"
{ 
                                            yylineno++; 
                                            yylval.text = strdup(yytext); 
                                            P("TEXT"); 
                                            return TEXT; 
                                        }
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 153 "markdown.lex"
{ 
                                            yylval.text = "</script>"; 
                                            P("SCRIPTEND"); 
                                            BEGIN INITIAL; 
                                            return SCRIPTEND;
                                        }
	YY_BREAK
/* style block */
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 165 "markdown.lex"
{
                                            yylval.text = strdup(yytext); 
                                            P("STYLESTART"); 
                                            BEGIN STYLEBLOCK; 
                                            return STYLESTART; 
                                        }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 171 "markdown.lex"
{ yylval.text = strdup(yytext); P("TEXT"); return TEXT; }
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 172 "markdown.lex"
{ 
                                            yylineno++; 
                                            yylval.text = strdup(yytext); 
                                            P("TEXT"); 
                                            return TEXT; 
                                        }
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 178 "markdown.lex"
{ 
                                            yylval.text = "</style>"; 
                                            P("STYLEEND"); 
                                            BEGIN INITIAL; 
                                            return STYLEEND;
                                        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 189 "markdown.lex"
{ yylval.text = strdup(yytext); P("TEXT"); return TEXT; }
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 190 "markdown.lex"
{ yylineno++; P("LINEBREAK"); return LINEBREAK; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 193 "markdown.lex"
ECHO;
	YY_BREAK
#line 1541 "markdown.lex.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(ESCAPE):
			case YY_STATE_EOF(CODEBLOCK):
			case YY_STATE_EOF(CODESPAN):
			case YY_STATE_EOF(XCODESPAN):
			case YY_STATE_EOF(INDENTLIST):
			case YY_STATE_EOF(SHTMLBLOCK):
			case YY_STATE_EOF(SCRIPTBLOCK):
			case YY_STATE_EOF(STYLEBLOCK):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 496 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 496 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 495);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 193 "markdown.lex"



int yywrap(){
    return 1;
}

    /*
    int main(int argc, char **argv){
        yyin = fopen(argv[1], "r");
        yylex();
        fclose(yyin);
    }
    */




